# Generated by Django 4.1.7 on 2023-04-18 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('victimemail', models.EmailField(max_length=254)),
                ('victimfullname', models.CharField(max_length=100)),
                ('mobno', models.CharField(max_length=100)),
                ('aadharno', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('typeofcrime', models.CharField(max_length=100)),
                ('incidentdatetime', models.DateTimeField()),
                ('detailsofincident', models.TextField()),
                ('suspect', models.CharField(max_length=100)),
                ('witness', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
