# Generated by Django 4.2 on 2023-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fir_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
