from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.
class FIR(models.Model):
    sno= models.AutoField(primary_key=True)
    username = models.CharField(max_length=100)
    useremail = models.EmailField()
    victimemail = models.EmailField()
    victimfullname = models.CharField(max_length=100)
    mobno = models.CharField(max_length=100)
    aadharno = models.CharField(max_length=100)
    address = models.TextField()
    district = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    typeofcrime = models.CharField(max_length=100)
    incidentdatetime = models.DateTimeField()
    detailsofincident = models.TextField()
    suspect = models.CharField(max_length=100)
    witness = models.CharField(max_length=100)

    timestamp = models.DateTimeField(default=now)
    status = models.BooleanField(default=False)
    solved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "FIR generated by "+ self.username + " - " + self.typeofcrime